version: '3.1'

services:

   
    hugo:
        build: 
            context: ./hugo
        image: hugobase
        volumes:
            - "./hugo:/hugodir"
        ports:
            - "1313:1313"

     