version: '3.1'

services:
    hugo:
        build: 
            context: ./hugo
            target: hugobase
        volumes:
            - ./hugo:/hugodir
            - ./hugo/public:/usr/share/nginx/html
        ports:
            - "1313:1313"

    nginx:
        build:
            context: ./hugo
            target: nginx-prod
        volumes:
            - ./hugo/public:/usr/share/nginx/html
        ports:
            - "8080:80"
        depends_on: 
            - hugo
       
       
   
    
        

    