version: '3.1'

services:
    hugo:
        build: 
            context: ./hugo
            target: hugobase
        volumes:
            - ./hugo:/hugodir
            - ./hugo/public:/usr/share/nginx/html
        ports:
            - "1313:1313"

    nginx:
        build:
            context: ./hugo
            target: nginx-prod
        volumes:
            - ./hugo/public:/usr/share/nginx/html
        ports:
            - "8080:80"
        depends_on: 
            - hugo
       
    wordpress:
        image: wordpress
        restart: always
        ports:
            - 8025:80
        environment:
            WORDPRESS_DB_HOST: hugo-docker-blog_wpdb_1
            WORDPRESS_DB_USER: exampleuser
            WORDPRESS_DB_PASSWORD: examplepass
            WORDPRESS_DB_NAME: exampledb
        volumes:
            - ./wordpress:/var/www/html  
    
    wpdb:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: exampledb
            MYSQL_USER: exampleuser
            MYSQL_PASSWORD: examplepass
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes:
            - ./wordpressdb:/var/lib/mysql


    