version: '3.1'

services:

   
    hugo:
        build: 
            context: .
        image: hugobase
        volumes:
            - "./hugo:/hugodir"
        ports:
            - "1313:1313"

    server:
        image: nginx
        volumes:
            - ./hugo/public:/usr/share/nginx/html
        ports:
            - "8080:80"
     